# Generated by Django 5.0 on 2024-01-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_foydalanuvchi_joylashuv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahsulot',
            name='like',
            field=models.ManyToManyField(blank=True, null=True, to='app.foydalanuvchi'),
        ),
    ]
