# Generated by Django 5.0 on 2024-01-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_mahsulot_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsulot',
            name='bonus',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='chegirma',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
