# Generated by Django 5.0 on 2024-01-02 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_foydalanuvchi_stared'),
    ]

    operations = [
        migrations.AddField(
            model_name='foydalanuvchi',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
