# Generated by Django 5.0 on 2024-01-02 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_foydalanuvchi_total_mahsulot_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foydalanuvchi',
            name='stared',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mahsulot',
            name='stared',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
