# Generated by Django 5.0 on 2024-01-03 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_foydalanuvchi_stared_alter_mahsulot_stared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foydalanuvchi',
            name='stared',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='foydalanuvchi',
            name='total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='mahsulot',
            name='stared',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='mahsulot',
            name='total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
