# Generated by Django 5.0 on 2024-01-03 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_foydalanuvchi_stared_alter_foydalanuvchi_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foydalanuvchi',
            name='stared',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='foydalanuvchi',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
