# Generated by Django 5.0 on 2024-01-07 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_mahsulot_stared_alter_mahsulot_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahsulot',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
    ]
