# Generated by Django 5.0 on 2024-01-07 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_mahsulot_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mahsulot',
            options={'ordering': ['stared']},
        ),
    ]
